name: CLEO 5 Test Build

on:
  push:
    paths-ignore:
    - ".github/*"
    - "*.md"
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Core - Build
        shell: cmd
        run: |
          set PLUGIN_SDK_DIR=%GITHUB_WORKSPACE%\third-party\plugin-sdk
          msbuild -m CLEO5.sln /property:Configuration=Release /property:Platform=GTASA

      - name: Core - Sign
        uses: x87/code-sign-action@develop
        with:
          certificate: '${{ secrets.DIG_KEY_CERT }}'
          password: '${{ secrets.DIG_KEY_PWD }}'
          certificatename: 'Seemann'
          description: 'CLEO 5'
          timestampUrl: 'http://timestamp.digicert.com'
          filename: './.output/Release/cleo.asi'

      - name: Core - VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_KEY }}
          files: './.output/Release/CLEO.asi'

      - name: Plugins - Build
        shell: cmd
        run: |
          set PLUGIN_SDK_DIR=%GITHUB_WORKSPACE%\third-party\plugin-sdk
          msbuild -m cleo_plugins/CLEO_Plugins.sln /property:Configuration=Release /property:Platform=x86

      - name: Plugins - Sign
        uses: x87/code-sign-action@develop
        with:
          certificate: '${{ secrets.DIG_KEY_CERT }}'
          password: '${{ secrets.DIG_KEY_PWD }}'
          certificatename: 'Seemann'
          description: 'CLEO 5 Plugin'
          timestampUrl: 'http://timestamp.digicert.com'
          folder: './cleo_plugins/.output'
          
      - name: Plugins - VirusTotal Scan
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_KEY }}
          files: './cleo_plugins/.output/*.cleo'

      - name: Gather Output Files
        id: prepare_archive
        shell: cmd
        run: |
          @REM create output directory
          mkdir .output\Release\cleo
          mkdir .output\Release\cleo\cleo_plugins

          @REM copy files
          copy third-party\bass\bass.dll .output\Release\bass.dll
          copy source\cleo_config.ini .output\Release\cleo\.cleo_config.ini
          copy cleo_plugins\.output\*.cleo .output\Release\cleo\cleo_plugins
          copy cleo_plugins\.output\*.ini .output\Release\cleo\cleo_plugins

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          compression-level: 0
          name: SA.CLEO5
          path: |
            .output\Release\*
            !.output\Release\*.pdb
            !.output\Release\*.lib
            !.output\Release\*.exp
